import type { Metadata } from 'next';
import { CookiesProvider } from 'next-client-cookies/server';
import './globals.css';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CookiesProvider>
          <Header />
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
